baseURL: "https://sbkv1.github.io/" 
title: Blog - Samir Paul
paginate: 5
theme: PaperMod
 
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

languageName: "English"
weight: 1
taxonomies:
  category: categories
  tag: tags
  series: series
menu:
    main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Technical blog made by developer for developers. Computer Science, Data Structures Algorithms, Networking, Artificial Intelligence and Coding Interview Prep."
    author: Samir Paul
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    ShowWordCount: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowFullTextinRSS: true
    ShowRssButtonInSectionTermList: true
    hideFooter: true
    ShowToc: true
    TocOpen: false
    hidemeta: false
    comments: false
    images: ["assets/banner-min.webp", "https://samirpaulb.github.io/assets/blog-featured-image-samirpaul-in-blog.webp"]

    profileMode:
        enabled: false
        title: Samir Paul
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Samir Paul"
        Content: >
           
<p align="center">
  <a href="#"> <img  alt="Welcome" src="https://raw.githubusercontent.com/SamirPaul1/SamirPaul1.github.io/main/assets/img/welcome.svg"/> </a>
</p>
<p style="font-family:Tinos"> I am an undergraduate student at the National Institute of Technology Durgapur. I enjoy problem-solving and coding. Always strive to bring 100% to the work I do. I am passionate about developing complex applications that solve real-world problems impacting millions of users. </p>

<p align="center"><a class="btn-lang" href="https://samirpaul1.github.io/resume" target = "_blank">Download CV</a></p>

---

<p align="center">
  <a href="#"> <img alt="Education" src="/assets/img/education.svg"/> </a>
</p>

> <a href="https://nitdgp.ac.in/" target = "_blank"><strong> NATIONAL INSTITUTE OF TECHNOLOGY DURGAPUR</strong></a>

B.Tech (Electronics and Communication Engineering) ```Nov 2020 - July 2024```
<p style="font-family:Tinos"> • 9/10 CGPA.</p>
<b> </b>

> <a href="#"><strong> SILIGURI BARADAKANTA VIDYAPITH</strong></a>

WBCHSE & WBBSE ```2013 - 2020```
<p style="font-family:Tinos"> • WBCHSE (Senior Secondary Class XII) 92.00% PCM & Computer Science.</p>
<p style="font-family:Tinos"> • WBBSE (Secondary Class X) 96.14% General Studies.</p>

---

<p align="center">
  <a href="#"> <img alt="Experience" src="/assets/img/experience.svg"/> </a>
</p>

> <a href="https://www.amazon.in/" target = "_blank"><strong> AMAZON</strong></a>

Machine Learning Trainee ```Jun 2022 - July 2022```
<p style="font-family:Tinos"> • Learned and implemented various concepts of Machine Learning(Supervised-Unsupervised Learning, Neural Networks).</p>
<b> </b>

> <a href="http://www.niti.gov.in/" target = "_blank"><strong> NITI AAYOG</strong></a>

Data Management and Analytics Intern ```July 2021 – Oct 2021```
<p style="font-family:Tinos"> • Worked with NDAP in the data sourcing workstream. Created and analysed datasets for PSUs and autonomous bodies.</p>
<p style="font-family:Tinos"> • Used Python NumPy and Pandas in Jupyter notebook to create and visualise PyCharts.</p>
<p style="font-family:Tinos"> • Worked on SDG Index and analysed the upcoming use of AR-VR in the non-gaming sector in India.</p>
<b> </b>

> <a href="https://www.thinkindiaorg.in/" target = "_blank"><strong> THINK INDIA</strong></a>

Public Policy Intern ```Jun 2021 - July 2021```
<p style="font-family:Tinos"> • Created reports and blog posts for Think India and worked under the guidance of the Nyaypravah organization.</p>

---

<p align="center">
  <a href="#"> <img alt="Coding Profiles" src="/assets/img/coding.svg"/> </a>
</p>

> <a href="#"><strong> Coding Profiles</strong></a>

<b>SamirPaul1</b> across coding platforms.
<p style="font-family:Tinos" align="center"><strong> <a href="https://github.com/SamirPaul1" target = "_blank"><b>GitHub</b></a> • <a href="https://leetcode.com/samirpaul1" target = "_blank"><b>LeetCode</b></a> • <a href="https://auth.geeksforgeeks.org/user/samirpaul1/" target = "_blank"><b>GeeksforGeeks</b></a> • <a href="https://www.codechef.com/users/samirpaul1" target = "_blank"><b>CodeChef</b></a> • <a href="https://www.hackerrank.com/samirpaul1" target = "_blank"><b>HackerRank</b></a> </strong></p>

---

> <a href="#"><strong> Languages And Tools</strong></a>
<p align="center">
  
<code  >
<img alt="Python" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/python.png">
</code>
<code >
<img alt="MySQL" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/mysql.png">
</code>
<code >
<img alt="Java" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/java.png">
</code>
<code >
<img alt="HTML5" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/html.png">
</code>
<code >
<img alt="CSS3" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/css.png">
</code>
<code >
<img alt="JavaScript" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/javascript.png" />
</code>
<code >
<img alt="C" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/c.png" />
</code>
<code >
<img alt="C++" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/cpp.png" />
</code>
<code >
<img alt="Git" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/git.png">
</code>
<code >
<img alt="Django" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/django.png">
</code>
<code >
<img alt="ReactJS" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/react.png">
</code>
<code >
<img alt="Powershell" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/powershell.png">
</code>
<code >
<img alt="Sublime" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/sublime.png">
</code>
<code >
<img alt="VS-Code" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/vscode.png" />
</code>
<code >
<img alt="Intellij" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/intelejidea.png" />
</code>
<code >
<img alt="Pycharm" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/pycharm.png" />
</code>
<code >
<img alt="Windows" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/windows.png">
</code>
<code >
<img alt="MacOS" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/macos.png">
</code>
<code>
<img alt="Linux" width="26px" src="https://raw.githubusercontent.com/SamirPaulb/assets/main/linux.png">
</code>

</p>  

---

<p align="center">
  <a href="#"> <img alt="Projects" src="/assets/img/projects.svg"/> </a>
</p>


### <i class="fas fa-code"></i> [DSAlgo](https://github.com/SamirPaul1/DSAlgo) ![GitHub Stars](https://img.shields.io/github/stars/SamirPaul1/DSAlgo?style=social)

This repository consists of many problems and their solutions in Python 3 on Data Structures and Algorithms which I have come across while Learning DSA on various competitive programming sites. The Git repo is available: [Here.⇗](https://github.com/SamirPaul1/DSAlgo)


### <i class="fas fa-code"></i> [Portfolio Website](https://samirpaul1.github.io/portfolio) 

A Project for making a blog website attaching about me, contacts, live-map location-services, send a message, all certificates, fetching all current activities on GitHub for opensource contributions. It is a fully customizable website also. The Git repo is available: [Here.⇗](https://github.com/SamirPaul1/portfolio)


### <i class="fas fa-code"></i> [Music Player](https://samirpaul1.github.io/music/)

A Music Player App developed using JavaScript, CSS, and HTML. The user can make collection of songs, click the Forward play, Backward play, Playlist loop and Shuffle music buttons to change the songs. The source code is available: [Here.⇗](https://github.com/samirpaul1/music)


### <i class="fas fa-code"></i> [CodeforcesVisualizer](https://samirpaul1.github.io/CodeforcesVisualizer/) 

Made a Codeforces Visualizer. Users can input any Username and can see particular user ratings as well as other pieces of information in the form of tables and graphs.(HTML,CSS,Jquery,JS charts,Codeforces API). The Git repo is available: [Here.⇗](https://github.com/SamirPaul1/CodeforcesVisualizer)


### <i class="fas fa-code"></i> [Make Notes App](https://samirpaul1.github.io/MakeNotes/) 

Users can Make Important Notes as well as save them for future reference. You can mark important as well as non-important which makes it very easy to distinguish between different notes.(Html,Bootstrap,CSS,Javascript). The Git repo is available: [Here.⇗](https://github.com/SamirPaul1/MakeNotes)


### <i class="fas fa-code"></i> [Weather App](https://samirpaul1.github.io/WeatherApp/)

A Weather App that pulls from the OpenWeatherMap API to allow users to search for and view the forecast in cities worldwide. Built with JavaScript, CSS, HTML, Theodinproject, OpenWeatherMap API. The Git repo is available: [Here.⇗](https://github.com/SamirPaul1/Weather)


### <i class="fas fa-code"></i> [Text File Compressor](https://samirpaul1.github.io/txt-compressor/) 

An online .txt file compressor, de-compressor tool uses Huffman Coding for Lossless Data Compression. An [Info Page](https://samirpaul1.github.io/txt-compressor/info.html) is also added about the compression technique and the compression ratio is also displayed. (HTML, CSS, PHP, Javascript). The Git repo is available: [Here.⇗](https://github.com/SamirPaul1/txt-compressor)


### <i class="fas fa-code"></i> [Online PDF Compressor](https://github.com/SamirPaul1/filecompressor) 

An online PDF file compression tool. Python Flask is used to upload a file to a temporary location on the server then using the PDFNetPython library that file gets reduced and automatically removed after 1 hour. (Python3, Flask, C, Shell, Nix, HTML, CSS, JavaScript). Source code available: [Here.⇗](https://github.com/SamirPaul1/filecompressor)


### <i class="fas fa-code"></i> [Linktree Clone](https://samirpaul1.github.io/link/) 

A simple webpage to group all profiles on social networks in one place. A clone of popular social media referencing site Linktree, under the MIT license. The website is made responsive (with HTML5 and CSS3). The GitHub repository is available: [Here.⇗](https://github.com/SamirPaul1/link)


    socialIcons:
        - name: GitHub
          url: "https://github.com/SamirPaul1"
        - name: LinkedIn
          url: "https://linkedin.com/in/SamirPaul"
        - name: Twitter
          url: "https://twitter.com/SamirPaulb"
        - name: Instagram
          url: "https://www.instagram.com/SamirPaulb"
        - name: Facebook
          url: "https://facebook.com/SamirPaulb"
        - name: Rss
          url: "index.xml"


    editPost:
        URL: "https://twitter.com/intent/follow?screen_name=SamirPaulb"
        Text: "Contact Author" # edit text
        appendFilePath: false # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    analytics:
        google:
            SiteVerificationTag: "vJAOBxbJTCK2vXG-hLFeGsoC9hXgFlCpuJJ8AcJLROQ"
        bing:
            SiteVerificationTag: "1A92FC2EC113F8616A21D76DA684A133"
        yandex:
            SiteVerificationTag: "fe6a06c57be84984"
        pinterest:
            SiteVerificationTag: "24bac6e1fbf1750de40d59bb788d9dd9"


    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: false # hide on single page
        linkFullImages: false
        image: "https://samirpaulb.github.io/assets/blog-featured-image-samirpaul-in-blog.webp"
        alt: "blog-featured-image"
        caption: "Technical blog"

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
