baseURL: "https://sbkv1.github.io/" 
title: Tech Blog 
paginate: 5
theme: PaperMod
 
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

languageName: "English"
weight: 1
taxonomies:
  category: categories
  tag: tags
  series: series
menu:
    main:
        - name: Links
          url: links
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Technical blog made by developer for developers. Computer Science, Data Structures Algorithms, Networking, Artificial Intelligence and Coding Interview Prep."
    author: Samir Paul
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    ShowWordCount: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowFullTextinRSS: true
    ShowRssButtonInSectionTermList: true
    hideFooter: true
    ShowToc: true
    TocOpen: false
    hidemeta: false
    comments: false
    images: ["assets/banner-min.webp", "https://samirpaulb.github.io/assets/blog-featured-image-samirpaul-in-blog.webp"]

    profileMode:
        enabled: false
        title: Tech Blog
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Samir Paul"
        Content: "I am an undergraduate student at the National Institute of Technology, Durgapur. I enjoy problem-solving and coding. I love solving questions on LeetCode and doing competitive programming. I am well-versed in Computer Science fundamentals like OOPS, Operating Systems, Database Management Systems, and Computer Networks and I also have a keen interest in High-Level System Design. I have built a few projects on Web Development using MongoDB, Express, ReactJS and Node.js, and App Development using Dart and Flutter. I am passionate about developing complex applications that solve real-world problems impacting millions of users. I always strive to bring 100% to the work I do."
             


    socialIcons:
        - name: GitHub
          url: "https://github.com/SamirPaul1"
        - name: LinkedIn
          url: "https://linkedin.com/in/SamirPaul"
        - name: Twitter
          url: "https://twitter.com/SamirPaulb"
        - name: Instagram
          url: "https://www.instagram.com/SamirPaulb"
        - name: Facebook
          url: "https://facebook.com/SamirPaulb"
        - name: Rss
          url: "index.xml"


    editPost:
        URL: "https://twitter.com/intent/follow?screen_name=SamirPaulb"
        Text: "Contact Author" # edit text
        appendFilePath: false # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    analytics:
        google:
            SiteVerificationTag: "K6He7FEDRxz7EgmCjUdIimKF8uTffswTPpCqs6l0CXU"
        bing:
            SiteVerificationTag: "1A92FC2EC113F8616A21D76DA684A133"
        yandex:
            SiteVerificationTag: "fe6a06c57be84984"
        pinterest:
            SiteVerificationTag: "24bac6e1fbf1750de40d59bb788d9dd9"


    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: false # hide on single page
        linkFullImages: false
        image: "https://samirpaulb.github.io/assets/blog-featured-image-samirpaul-in-blog.webp"
        alt: "blog-featured-image"
        caption: "Technical blog"

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
